name: Build & Upload APK to GitHub Release

on:
  release:
    types: [created]  # Chỉ trigger khi tạo release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install SDK components
      run: sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33" "ndk;27.0.12077973" "cmake;3.22.1"

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/27.0.12077973" >> local.properties

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleNonRoot_gameRelease

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/nonRoot_game/release/app-nonRoot_game-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
